package com.neeva.app.neevascope

import android.net.Uri
import java.net.URLEncoder
import java.nio.charset.StandardCharsets

private enum class Matcher(val regex: Regex) {
    BESTBUY(regex = Regex("/([0-9]*).p$")),
    CCC_AMAZON_PRODUCT(regex = Regex("/product/(\\w*)")),
    AMAZON_PACKAGE_TRACKING(regex = Regex("/progress-tracker/package/")),
    AMAZON_ID_FROM_RERFERRAL(regex = Regex("/g/r/.*/dp/(\\w*).*"))
}

class CanonicalUrl {

    // StripMobile is removing some patterns associated with mobile urls.
    fun stripMobile(url: Uri): Uri {
        var newAuthority = url.authority
        newAuthority?.let {
            val starterRegex = "^(mobile|m)\\."
            newAuthority = Regex(starterRegex).replace(it, "www.")
        }

        newAuthority?.let {
            val mobileWikipediaRegex = "^(..)\\.m\\.wikipedia\\.org"
            newAuthority = Regex(mobileWikipediaRegex).replace(it, "$1.wikipedia.org")
        }

        return url.buildUpon().authority(newAuthority).build()
    }

    // ref: https://github.com/neevaco/neeva/blob/master/webcrawl/url.go
    private fun canonicalURLInternal(url: Uri): Uri {
        val builder = Uri.Builder()

        var urlAuth = stripMobile(url).authority?.lowercase()
        var urlPath = url.path
        var urlQuery = url.encodedQuery

        // All wirecutter.com URLs moved permanently (301s) to nytimes.com/wirecutter.
        val prefixes = listOf(
            "wirecutter.com",
            "www.wirecutter.com",
            "thewirecutter.com",
            "www.thewirecutter.com"
        )

        // Example, https://www.thewirecutter.com/lists/how-to-sleep-well-or-at-least-better-while-traveling/
        if (prefixes.contains(urlAuth)) {
            urlAuth = "www.nytimes.com"
            urlPath = "/wirecutter$urlPath"
        }

        when (urlAuth) {
            "assoc-redirect.amazon.com" -> {
                // Example, https://assoc-redirect.amazon.com/g/r/https://www.amazon.com/dp/B07JJJJCVP?tag=cnet-api-20&amp;linkCode=ogi&amp;th=1&amp;psc=1&amp;ascsubtag=ag%3A06304a6d-5bbd-442d-802b-8ce21cf063eb%7Cvg%3A___VIEW_GUID___%7Cst%3Adtp
                val match = Matcher.AMAZON_ID_FROM_RERFERRAL.regex.find(urlPath.toString())
                match?.destructured?.match?.groups?.get(1)?.let {
                    urlAuth = "www.amazon.com"
                    urlPath = "/dp/" + it.value
                    urlQuery = ""
                }
            }

            "www.amazon.com" -> {
                urlPath?.let { path ->
                    // Example, https://www.amazon.com/ask/questions/asin/B085T8CDLZ/ref=cm_cd_dp_lla_ql_ll/142-3478057-6455969
                    val index = path.indexOf("/ref=")
                    if (index >= 0) {
                        if (Matcher.AMAZON_PACKAGE_TRACKING.regex.containsMatchIn(url.toString())) {
                            return Uri.EMPTY
                        }
                        urlPath = path.substring(0, index)
                    }
                }

                val parts = urlPath?.split('/')
                if (parts?.count() == 4 && parts[2] == "dp") {
                    // Example, https://www.amazon.com/SIMARI-Womens-Barefoot-Walking-Black/dp/B07R8M8FK6
                    urlPath = "/dp/" + parts[3]
                } else if (parts?.count() == 4 && parts[1] == "gp") {
                    // Example, https://www.amazon.com/gp/product/164152247X
                    urlPath = "/dp/" + parts[3]
                } else if (parts?.count() == 3 && parts[2] == "s") {
                    // Example, https://www.amazon.com/best-pillows/s?k=best+pillows
                    urlPath = "/s"
                }

                // Only keep URL params in keepQueryParams.
                for (param in queryParamsToKeepFromAmazonUrl) {
                    if (url.getQueryParameter(param) != null) {
                        builder.appendQueryParameter(
                            param,
                            URLEncoder.encode(
                                url.getQueryParameter(param),
                                StandardCharsets.UTF_8.name()
                            )
                        )
                    }
                }
                if (
                    url.getQueryParameter("pg") != null &&
                    url.getQueryParameter("pg") != "1"
                ) {
                    // Example, https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Cases/zgbs/pc/572238/ref=zg_bs_pg_1/132-6106119-9988022?encoding=UTF8&pg=2
                    builder.appendQueryParameter(
                        "pg",
                        URLEncoder.encode(
                            url.getQueryParameter("pg"),
                            StandardCharsets.UTF_8.name()
                        )
                    )
                }
                urlQuery = builder.build().query
            }

            "bestbuy.7tiv.net" -> {
                // Example, https://bestbuy.7tiv.net/c/159047/633495/10014?prodsku=5760801&u=https%3A%2F%2Fapi.bestbuy.com%2Fclick%2F-%2F5760801%2Fpdp&subId1=cn-4645dc5da55e4f78affce38ecc13f56e-dtp-us&subId3=xid:fr1592428206259fai
                if (url.getQueryParameter("prodsku") != null) {
                    urlAuth = "www.bestbuy.com"
                    urlPath = "/site/" + url.getQueryParameter("prodsku") + ".p"
                    urlQuery = ""
                } else if (url.getQueryParameter("u") != null) {
                    val parsed = Uri.parse(url.getQueryParameter("u"))
                    if (parsed.authority == "www.bestbuy.com") {
                        val matches = Matcher.BESTBUY.regex.findAll(parsed.path.toString())
                        matches.first().let {
                            urlAuth = parsed.authority
                            urlPath = "/site" + it.value
                            urlQuery = ""
                        }
                    }
                }
            }

            "www.bestbuy.com" -> {
                // Example, https://www.bestbuy.com/site/bosch-500-series-4-0-cu-ft-15-cycle-high-efficiency-compact-electric-dryer-white/8808216.p?skuId=8808216
                val matches = Matcher.BESTBUY.regex.findAll(urlPath.toString())
                matches.first().let {
                    urlPath = "/site" + it.value
                    urlQuery = ""
                }
            }

            "camelcamelcamel.com", "www.camelcamelcamel.com" -> {
                // Example, https://camelcamelcamel.com/beyerdynamic-990-PRO-250-ohm/product/B010IJ9W1U
                val matches = Matcher.CCC_AMAZON_PRODUCT.regex.findAll(urlPath.toString())
                matches.first().let {
                    urlPath = it.value
                    urlQuery = ""
                }
            }

            "www.target.com" -> {
                // Example, https://www.target.com/p/safety-1st-easy-grip-brush-38-comb-set-white/-/A-14061607
                val parts = urlPath?.split('/')
                if (parts?.count() == 4 && parts[1] == "p" && parts[2] == "-") {
                    urlPath = "/p/-/" + parts[3]
                    urlQuery = ""
                } else if (parts?.count() == 5 && parts[1] == "p" && parts[3] == "-") {
                    urlPath = "/p/-/" + parts[4]
                    urlQuery = ""
                }
            }

            "www.walmart.com" -> {
                // Example, https://www.walmart.com/blocked?url=L2lwLzM5NjAxNDcz&uuid=aae777c0-3e64-11eb-a66e-bf39453d2c36&vid=&g=a
                urlPath?.split('/')
                    ?.takeIf { it.count() == 4 && it[1] == "ip" }
                    ?.let {
                        urlPath = "/ip/" + it[3]
                        urlQuery = ""
                    }
            }

            "www.homedepot.com" -> {
                // Example, https://www.homedepot.com/p/Amana-5-0-cu-ft-Gas-Range-in-Stainless-Steel-AGR6603SFS/300144108?irgwc=1&cm_mmc=afl-ir-50053-459920-&clickid=ylhSpnVDZxyORPEwUx0Mo36HUkiTxayT0y%3As3k0
                if (urlPath.toString().startsWith("/p")) {
                    urlQuery = ""
                }
            }

            else -> {
                urlAuth
                    ?.takeIf { stackDomains.contains(it) }
                    ?.let {
                        val parts = urlPath?.split('/')
                        if (
                            parts?.count() == 4 && parts[1] == "questions" && parts[2] != "tagged"
                        ) {
                            urlPath = parts.take(3).joinToString("/")
                        } else if (
                            parts?.count() == 5 && parts[1] == "questions" && parts[4] == ""
                        ) {
                            urlPath = parts.take(3).joinToString("/")
                        }
                    }
            }
        }

        urlAuth
            ?.takeUnless { notStripSlashDomains.contains(it.removePrefix("www.")) }
            ?.let {
                urlPath = urlPath?.removeSuffix("/")
            }

        val canonicalizedUrl = Uri.Builder()
            .scheme("https")
            .authority(urlAuth)
            .path(urlPath)
            .encodedQuery(urlQuery)
            .build()

        return stripQueryParam(canonicalizedUrl)
    }

    private fun stripQueryParam(url: Uri): Uri {
        val queryParamToKeep = url.authority
            ?.let { keepQueryParamDomains[it.removePrefix("www.")] }
            ?: return url

        val builder = Uri.Builder()

        // Only keep URL params in keepQueryParams.
        val queryParams = url.queryParameterNames
            .filter { queryParamToKeep.contains(it) }
            .sorted()

        queryParams.let {
            if (it.isNotEmpty()) {
                it.forEach { param ->
                    builder.appendQueryParameter(
                        param,
                        URLEncoder.encode(
                            url.getQueryParameter(param),
                            StandardCharsets.UTF_8.name()
                        )
                    )
                }
            }
        }

        val urlQuery = builder.build().query
        return url.buildUpon().encodedQuery(urlQuery).build()
    }

    // canonicalURLV3Internal is the same as canonicalUrlInternal, but with additional logic.
    private fun canonicalURLV3Internal(url: Uri): Uri {
        val canonicalizedUrl = canonicalURLInternal(url)
        if (canonicalizedUrl != Uri.EMPTY) {
            val builder = Uri.Builder()
            var urlHost = canonicalizedUrl.host
            var urlPath = canonicalizedUrl.path
            var urlQuery = canonicalizedUrl.encodedQuery
            var trimmedHost = urlHost?.removePrefix("www.")

            if (trimmedHost != urlHost) {
                // Example, https://www.martinfowler.com/articles/microservices.html
                if (stripWWWDomains.contains(trimmedHost)) {
                    urlHost = trimmedHost
                }
            } else {
                // Example, https://www1.milwaukeetool.com/Innovations/M12
                trimmedHost = urlHost?.removePrefix("www1.")
                if (stripWWWDomains.contains(trimmedHost)) {
                    urlHost = trimmedHost
                }
            }

            if (stripWWWDomains.contains(trimmedHost)) {
                urlHost = trimmedHost
            }
            // Example, https://www.w3schools.com/SQL/sql_update.asp
            if (lowerPathDomains.contains(trimmedHost)) {
                urlPath = urlPath?.lowercase()
            }

            if (stackDomains.contains(urlHost)) {
                // Sometimes there is number associated after the question text
                // Example, https://stackoverflow.com/questions/1703228/how-can-i-clear/16222877
                val parts = urlPath?.split('/')?.toMutableList()
                if (
                    parts?.count() == 5 && parts[1] == "questions" && parts[2] != "tagged"
                ) {
                    urlPath = parts.take(3).joinToString("/")
                } else if (
                    (parts?.count() == 4 || parts?.count() == 5) && parts[1] == "q"
                ) {
                    parts[1] = "questions"
                    urlPath = parts.take(3).joinToString("/")
                }
            }

            if (urlHost == "www.amazon.com") {
                queryParamsToKeepFromAmazonUrl.forEach { param ->
                    // Example, https://www.amazon.com/gp/help/customer/display.html?nodeId=GTPNKDGX2ZJ3H43U
                    if (canonicalizedUrl.getQueryParameter(param) != null) {
                        builder.appendQueryParameter(
                            param,
                            URLEncoder.encode(
                                canonicalizedUrl.getQueryParameter(param).toString().lowercase(),
                                StandardCharsets.UTF_8.name()
                            )
                        )
                    }
                }
                if (
                    canonicalizedUrl.getQueryParameter("pg") != null &&
                    canonicalizedUrl.getQueryParameter("pg") != "1"
                ) {
                    builder.appendQueryParameter(
                        "pg",
                        URLEncoder.encode(
                            canonicalizedUrl.getQueryParameter("pg").toString().lowercase(),
                            StandardCharsets.UTF_8.name()
                        )
                    )
                }
                urlQuery = builder.build().query
            }

            return canonicalizedUrl
                .buildUpon()
                .authority(urlHost)
                .path(urlPath)
                .encodedQuery(urlQuery)
                .build()
        }
        return Uri.EMPTY
    }

    fun canonicalizeUrl(url: Uri): Uri {
        return if (canonicalURLV3Internal(url) == Uri.EMPTY) {
            url
        } else {
            canonicalURLV3Internal(url)
        }
    }

    private val notStripSlashDomains = listOf(
        "asos.com",
        "revolve.com",
        "westelm.com"
    )

    private val queryParamsToKeepFromAmazonUrl = listOf(
        "docId", "id", "k", "me", "messageID", "node", "nodeId", "page", "seller",
        "srs", "threadID", "rh", "zipcode"
    )

    private val keepQueryParamDomains: Map<String, Map<String, Boolean>> = mapOf(
        "abt.com" to mapOf(),
        "apple.com" to mapOf(
            "device1" to true,
            "device2" to true,
            "device3" to true,
            "modelList" to true
        ),
        "ashleyfurniture.com" to mapOf(),
        "ballarddesigns" to mapOf(),
        "bedbathandbeyond.com" to mapOf(),
        "biglots.com" to mapOf(),
        "bloomingdales.com" to mapOf("id" to true),
        "bombas.com" to mapOf(),
        "brooksbrothers.com" to mapOf(),
        "buybuybaby.com" to mapOf(),
        "calvinklein.us" to mapOf(),
        "coach.com" to mapOf(),
        "columbia.com" to mapOf(),
        "converse.com" to mapOf(),
        "dell.com" to mapOf("driverid" to true),
        "etsy.com" to mapOf("q" to true),
        "finishline.com" to mapOf("styleId" to true, "colorId" to true),
        "forever21.com" to mapOf("br21" to true),
        "frontgate.com" to mapOf(),
        "godoc.org" to mapOf(),
        "golang.org" to mapOf(),
        "goodreads.com" to mapOf("shelf" to true, "page" to true, "view" to true),
        "jcrew.com" to mapOf(
            "brand" to true, "color" to true,
            "discount" to true,
            "fit" to true,
            "size" to true
        ),
        "katespade.com" to mapOf(),
        "luckybrand.com" to mapOf(),
        "mackage.com" to mapOf(),
        "macys.com" to mapOf("ID" to true, "id" to true),
        "madewell.com" to mapOf(),
        "michaelkors.com" to mapOf(),
        "mytheresa.com" to mapOf(),
        "newbalance.com" to mapOf(),
        "nordstrom.com" to mapOf(),
        "onekingslane.com" to mapOf(),
        "pacsun.com" to mapOf(),
        "patagonia.com" to mapOf("productid" to true),
        "pkg.go.dev" to mapOf(),
        "poshmark.com" to mapOf(),
        "potterybarn.com" to mapOf("words" to true),
        "potterybarnkids.com" to mapOf("words" to true),
        "ralphlauren.com" to mapOf(),
        "rei.com" to mapOf(),
        "saksfifthavenue.com" to mapOf(),
        "saksoff5th.com" to mapOf(),
        "sephora.com" to mapOf(),
        "shopbop.com" to mapOf(),
        "staples.com" to mapOf(),
        "talbots.com" to mapOf(),
        "thecompanystore.com" to mapOf(),
        "ulta.com" to mapOf("productId" to true),
        "underarmour.com" to mapOf(),
        "us.jimmychoo.com" to mapOf(),
        "us.puma.com" to mapOf(),
        "vince.com" to mapOf(),
        "wayfair.com" to mapOf("goto" to true, "keyword" to true),
        "westelm.com" to mapOf("words" to true),
        "worldmarket.com" to mapOf(),
        "ysl.com" to mapOf(),
    )

    // Keep in sync with py/neeva/ranking/utils.py
    private val stackDomains = listOf(
        "askubuntu.com",
        "mathoverflow.net",
        "serverfault.com",
        "stackapps.com",
        "stackexchange.com",
        "stackoverflow.com",
        "superuser.com"
    )

    private val stripWWWDomains = listOf(
        "0x65.dev",
        "1040.com",
        "3480-3590-data-conversion.com",
        "4bes.nl",
        "599cd.com",
        "7-zip.org",
        "aaai.org",
        "accessibilityresources.org",
        "activatejavascript.org",
        "addall.com",
        "adilapapaya.com",
        "adoodle.org",
        "adventureworks.org",
        "advertisingview.com",
        "afb.org",
        "aggregate.org",
        "agiledata.org",
        "agilemodeling.com",
        "agiliq.com",
        "ai-startups.org",
        "aidanhogan.com",
        "aishack.in",
        "algostructure.com",
        "allhotkeys.com",
        "allmenus.com",
        "alpinelinux.org",
        "amazon.jobs",
        "ammyy.com",
        "ampsoft.net",
        "amundsen.com",
        "andrewberls.com",
        "angusj.com",
        "annaporterartist.com",
        "any-video-converter.com",
        "aonprd.com",
        "aosabook.org",
        "apache.org",
        "api-data.com",
        "applian.com",
        "applied-survey-methods.com",
        "apycom.com",
        "archive.org",
        "archiveofourown.org",
        "arothuis.nl",
        "asawicki.info",
        "asi-ware.com",
        "asicguru.com",
        "audd.io",
        "audiosciencereview.com",
        "audioxpress.com",
        "austinrochford.com",
        "austintexas.gov",
        "autoclicker.cc",
        "avajava.com",
        "avi-writer.com",
        "avlusa.com",
        "azuredevopslabs.com",
        "babelstone.co.uk",
        "babynames.com",
        "ballotpedia.org",
        "basicagency.com",
        "bbeditextras.org",
        "beach.io",
        "beginnerjavascript.com",
        "bernardmarr.com",
        "beyondcorp.com",
        "beyondlogic.org",
        "biblehub.com",
        "bieglercpa.com",
        "bing.com",
        "biostat.wisc.edu",
        "bits-pilani.ac.in",
        "blendermarket.com",
        "blog.ezekielekunola.com",
        "blog.google",
        "blooberry.com",
        "bluecrossnc.com",
        "bmdynamics.com",
        "boardgamegeek.com",
        "bogotobogo.com",
        "boldcontrol.com",
        "bostongis.com",
        "branchci.com",
        "brandnewbox.com",
        "brendanfong.com",
        "brendangregg.com",
        "brennan.id.au",
        "brinckerhoff.org",
        "browser-update.org",
        "browsersync.io",
        "btechsmartclass.com",
        "btobconnect.com",
        "business.gov.au",
        "busybox.net",
        "bytedude.com",
        "cairographics.org",
        "calculator.com",
        "caniuse.com",
        "careercup.com",
        "casectrl.com",
        "catb.org",
        "caveofprogramming.com",
        "cbs58.com",
        "cburch.com",
        "ccasantafe.org",
        "cesium.com",
        "cfn.upenn.edu",
        "chapsas.com",
        "charbase.com",
        "cheatengine.org",
        "chercher.tech",
        "chocolatey.org",
        "chrisnicoll.net",
        "christoolivier.com",
        "chromestatus.com",
        "cinemark.com",
        "citibank.co.uk",
        "classdojo.com",
        "classicperform.com",
        "classicshell.net",
        "claudiajs.com",
        "clinicaltrials.gov",
        "cliqz.com",
        "clojure.org",
        "cmmiinstitute.com",
        "cobbaut.be",
        "cocoadevcentral.com",
        "codecguide.com",
        "codeinwp.com",
        "codemoji.com",
        "codenames.plus",
        "coderanch.com",
        "coderrocketfuel.com",
        "codinghelmet.com",
        "codingsans.com",
        "cohascodpc.com",
        "coinranking.com",
        "colchesterdigital.org.uk",
        "coletiv.com",
        "color-ize.com",
        "colormatters.com",
        "community.spiceworks.com",
        "compose.com",
        "computersciencewiki.org",
        "comscigate.com",
        "configcat.com",
        "connectnc.com",
        "consultesoft.com",
        "contactout.com",
        "contextures.com",
        "controlflow.com",
        "convert-units.info",
        "converteverything.com",
        "convertstring.com",
        "cookbook-r.com",
        "copymydata.com",
        "corelangs.com",
        "coronavirus.in.gov",
        "cosinekitty.com",
        "countrycode.org",
        "coursescript.com",
        "cplusplus.com",
        "cpp.sh",
        "crunchbase.com",
        "cryptologie.net",
        "cryptomuseum.com",
        "cs-fundamentals.com",
        "cs.auckland.ac.nz",
        "cs.colby.edu",
        "cs.dartmouth.edu",
        "cs.ioc.ee",
        "cs.jhu.edu",
        "cs.rochester.edu",
        "csci.csusb.edu",
        "cse.buffalo.edu",
        "csit-sun.pub.ro",
        "css-infos.net",
        "cssanalyzer.com",
        "cssmine.com",
        "cssportal.com",
        "ctan.org",
        "ctimls.com",
        "cvshealth.com",
        "cybercircuits.co.nz",
        "cyberdriveillinois.com",
        "dagster.io",
        "danorlovsky.tech",
        "datafordemocracy.org",
        "datagenetics.com",
        "datatables.net",
        "davidmlane.com",
        "davidokwii.com",
        "davidsottimano.com",
        "dba-oracle.com",
        "dbvis.com",
        "deadlybossmods.com",
        "debuggable.com",
        "debuggex.com",
        "december.com",
        "dejazzer.com",
        "delimitware.com",
        "delphic.me.uk",
        "derekgourlay.com",
        "dermnetnz.org",
        "designcise.com",
        "developer.amazon.com",
        "dir.ca.gov",
        "discourse.org",
        "dkim.org",
        "docs.opencv.org",
        "dofactory.com",
        "doordashstore.com",
        "dos.myflorida.com",
        "doyourownpestcontrol.com",
        "dph.illinois.gov",
        "dpriver.com",
        "drububu.com",
        "ds100.org",
        "dshs.texas.gov",
        "dualwriter.com",
        "dyn-web.com",
        "easy-tensorflow.com",
        "ec2instances.info",
        "echoecho.com",
        "ecma-international.org",
        "economics.emory.edu",
        "economics.utoronto.ca",
        "ecpannualmeeting.com",
        "edd.ca.gov",
        "edwardthomson.com",
        "effbot.org",
        "eksworkshop.com",
        "elinux.org",
        "emailaddressmanager.com",
        "enable-javascript.com",
        "encorebusiness.com",
        "endmemo.com",
        "enlp.eu.com",
        "eprosima.com",
        "epubor.com",
        "erg.abdn.ac.uk",
        "essenceglobal.com",
        "eventhelix.com",
        "evermap.com",
        "everythingcomputerscience.com",
        "exifdata.com",
        "exiftool.org",
        "expressflow.com",
        "expressionsstores.com",
        "extracttable.com",
        "ezfn.dev",
        "facebook.design",
        "farazpatankar.com",
        "favorites-menu.com",
        "festi.info",
        "filesmerge.com",
        "fintechweekly.com",
        "finviz.com",
        "firehydrant.io",
        "fivestars.blog",
        "fixyourownprinter.com",
        "flagguys.com",
        "flalottery.com",
        "flathub.org",
        "flatpak.org",
        "fleethub.shell.com",
        "flightclub.com",
        "floydhilton.com",
        "fofxacademy.com",
        "fontawesome.cc",
        "fraudaid.com",
        "freedesktop.org",
        "freeonlineflashlight.com",
        "freepdfconvert.com",
        "freertos.org",
        "freeviewnz.tv",
        "fromtexttospeech.com",
        "frontline.vc",
        "fueleconomy.gov",
        "fullpagescreencapture.com",
        "fws.gov",
        "gaijin.at",
        "game-debate.com",
        "gamersdecide.com",
        "gammon.com.au",
        "gcaltoolkit.com",
        "gdeepak.com",
        "geocene.com",
        "geoffchappell.com",
        "geomidpoint.com",
        "getadblock.com",
        "gettheburger.com",
        "getyarn.io",
        "ghostscript.com",
        "ginifab.com",
        "git-scm.com",
        "github.com",
        "gitj.com",
        "gitmemory.com",
        "gjermundbjaanes.com",
        "glmoperations.com",
        "gmail.com",
        "gnupg.org",
        "godoc.org",
        "goer.org",
        "gofullbuild.com",
        "goldensoft.org",
        "golinks.io",
        "gonetspeed.com",
        "goofle.com",
        "google.com",
        "google.org",
        "gotthelook.com",
        "gradient.com",
        "gradschool.fsu.edu",
        "grow.google",
        "grpc.io",
        "gruntwork.io",
        "grymoire.com",
        "gsuite.google.com",
        "gsw.edu",
        "gtcc.edu",
        "guidgenerator.com",
        "gutenberg.org",
        "gzip.org",
        "hackernoon.com",
        "hanab.live",
        "handholdreport.com",
        "happyzebra.com",
        "harborfreight.com",
        "haselt.com",
        "hashtagopen.com",
        "haynerlibrary.org",
        "hdrhistogram.org",
        "hdtuto.com",
        "healow.com",
        "healthychildren.org",
        "helenanderson.co.nz",
        "hex2rgba.devoth.com",
        "hexus.net",
        "hl7.org",
        "honorless.net",
        "htmlandcssbook.com",
        "htmldog.com",
        "htmlescape.net",
        "htmlhelp.com",
        "hyperlinkcode.com",
        "ibo.org",
        "iconarchive.com",
        "ics.forth.gr",
        "ideone.com",
        "ieee802.org",
        "ietf.org",
        "igniterealtime.org",
        "igs.berkeley.edu",
        "ilga.gov",
        "illinoiswildflowers.info",
        "imageai.org",
        "imei24.com",
        "imeipro.info",
        "immixgroup.com",
        "immunize.org",
        "included.vc",
        "infinityworks.com",
        "informationisbeautiful.net",
        "informationweek.com",
        "interactivebrokers.com",
        "internettrafficreport.com",
        "invoice.land",
        "iosrjen.org",
        "ipadacademy.com",
        "ipaddressguide.com",
        "iphoneresolution.com",
        "iremover.org",
        "ironspider.ca",
        "ishadeed.com",
        "iterm2.com",
        "itl.nist.gov",
        "iunlocker.com",
        "java.com",
        "java2novice.com",
        "javascripter.net",
        "javascriptkit.com",
        "jayconrod.com",
        "jazkarta.com",
        "jdash.io",
        "jekyll.math.byuh.edu",
        "jkorpela.fi",
        "jmlr.org",
        "jnis.ac.in",
        "jochenhebbrecht.be",
        "joshwcomeau.com",
        "jrgraphix.net",
        "json.org",
        "jsondiff.com",
        "jsonrpc.org",
        "jsonschema.net",
        "juliaobserver.com",
        "jxplorer.org",
        "kalmstrom.com",
        "katacoda.com",
        "kbdedit.com",
        "keefegroup.com",
        "kenrockwell.com",
        "key.me",
        "keybr.com",
        "keyxl.com",
        "khou.com",
        "khronos.org",
        "kidsmathgamesonline.com",
        "kimsereylam.com",
        "kingcounty.gov",
        "kirenz.com",
        "kite.com",
        "kodlogs.com",
        "kuow.org",
        "kvance.com",
        "kwcontrolpanel.com",
        "kyjustice.org",
        "lab.dotjay.com",
        "labs.ovh.com",
        "labservices.com",
        "lakesnwoods.com",
        "laserscanningforum.com",
        "latex-cookbook.net",
        "lazesoft.com",
        "ldapbrowsermac.com",
        "learnabout-electronics.org",
        "learnersdictionary.com",
        "learnyouahaskell.com",
        "lethain.com",
        "lexjansen.com",
        "linear.app",
        "linkedbuildingdata.net",
        "linux-sxs.org",
        "linuxcertified.com",
        "linuxcommand.org",
        "linuxconsultant.info",
        "linuxmint.com",
        "llvm.org",
        "loadsystems.co.uk",
        "lockheedmartin.com",
        "login.gov",
        "louisiana.edu",
        "lsu.edu",
        "lucenetutorial.com",
        "lukasa.co.uk",
        "lzone.de",
        "m2mate.com",
        "m3db.io",
        "m4vgear.com",
        "machenxiao.com",
        "macsx.com",
        "madebyevan.com",
        "magnum.graphics",
        "man7.org",
        "mangolassi.it",
        "manuelmeyer.net",
        "mapleprimes.com",
        "markdownpad.com",
        "marmalade-repo.org",
        "martinfowler.com",
        "marvelousdesigner.com",
        "masteringemacs.org",
        "material.io",
        "math-cs.gordon.edu",
        "math-linux.com",
        "math.cmu.edu",
        "math.nsc.ru",
        "math.temple.edu",
        "mathbits.com",
        "mathopenref.com",
        "mathpapa.com",
        "mathsisfun.com",
        "mathwords.com",
        "maxi-pedia.com",
        "maya.vc",
        "mbmlbook.com",
        "mbsdirect.com",
        "measurethat.net",
        "med.stanford.edu",
        "mediaplayer10.com",
        "medicalbiostatistics.com",
        "messenger.com",
        "metabase.com",
        "mhacks.org",
        "mikulskibartosz.name",
        "militarycac.com",
        "milwaukeetool.com",
        "minecraft.net",
        "modelzoo.co",
        "molbiotools.com",
        "monkeytype.com",
        "montgomerycountymd.gov",
        "moonbooks.org",
        "mordorintelligence.com",
        "movable-type.co.uk",
        "mtch.com",
        "mtsu.edu",
        "multipath-tcp.org",
        "mundanecode.com",
        "mutualfunds.com",
        "mux.com",
        "myaccountviewonline.com",
        "myanimelist.net",
        "mybookmarks.com",
        "mybyways.com",
        "mycamra.com",
        "myfavoritestoolbar.net",
        "myflix.pk",
        "mylife.com",
        "mystore411.com",
        "nami.org",
        "nature.com",
        "navicat.com",
        "needtags.com",
        "neevia.com",
        "net-informations.com",
        "netmarketshare.com",
        "networksorcery.com",
        "newlook.dteenergy.com",
        "nexthop.com.au",
        "nghttp2.org",
        "nicadd.niu.edu",
        "nivas.hr",
        "nj.gov",
        "njcourts.gov",
        "nobadmemories.com",
        "normatecrecovery.com",
        "noteburner.com",
        "noterepeat.com",
        "nsf.gov",
        "nssurge.com",
        "number2word.com",
        "numbertheory.org",
        "numpy.org",
        "oag.ca.gov",
        "office.live.com",
        "officeoneonline.com",
        "oklahoman.com",
        "omim.org",
        "omniglot.com",
        "ongres.com",
        "online-toolz.com",
        "onlinelibrary.wiley.com",
        "onlinestatbook.com",
        "opcdatahub.com",
        "openbookproject.net",
        "opencamera.org.uk",
        "openmymind.net",
        "opensemanticsearch.org",
        "opentechguides.com",
        "openzim.org",
        "opinionatedgeek.com",
        "opussoftware.com",
        "orau.gov",
        "orioniconlibrary.com",
        "osi-model.com",
        "osquery.io",
        "osta.org",
        "outlookonthedesktop.com",
        "overlay-tech.com",
        "p-nand-q.com",
        "pacificcontrols.net",
        "pacificresearchplatform.org",
        "packetfabric.com",
        "pagetutor.com",
        "pamela.biz",
        "panic.com",
        "paperswithcode.com",
        "pastebin.pl",
        "paulirish.com",
        "paulund.co.uk",
        "paulwhippconsulting.com",
        "percentage-change-calculator.com",
        "perceptualedge.com",
        "permadi.com",
        "persistiq.com",
        "peter-hoffmann.com",
        "phanderson.com",
        "phonespell.org",
        "phoronix.com",
        "physics.princeton.edu",
        "piware.de",
        "planetmath.org",
        "planetpython.org",
        "plants.usda.gov",
        "platt.com",
        "playdeck.net",
        "pocketsoap.com",
        "polymorphe.org",
        "ports1961.com",
        "postgis.net",
        "postgresguide.com",
        "ppp.uiuc.edu",
        "practicalcryptography.com",
        "printuniversal.com",
        "probuilds.net",
        "processing.org",
        "programata.bg",
        "programmersought.com",
        "programming-idioms.org",
        "psharvard.org",
        "publichealth.lacounty.gov",
        "pylint.org",
        "pyqtgraph.org",
        "python-ds.com",
        "python-future.org",
        "python.omics.wiki",
        "pythonprogramming.net",
        "qcad.org",
        "quadibloc.com",
        "quadtonerip.com",
        "quantilus.com",
        "quintagroup.com",
        "quirksmode.org",
        "quora.com",
        "rau-deaver.org",
        "razorsql.com",
        "rd-alliance.org",
        "react-hook-form.com",
        "reactenlightenment.com",
        "reactnative.com",
        "readabilityformulas.com",
        "rebol.com",
        "recordnotfound.com",
        "redislabs.com",
        "reederapp.com",
        "refreshyourcache.com",
        "regexlib.com",
        "remapkey.com",
        "research.ibm.com",
        "reset.build",
        "restapitutorial.com",
        "retool.com",
        "rhymezone.com",
        "ribice.ba",
        "rion.io",
        "riot.im",
        "rob-mcculloch.org",
        "rosettacode.org",
        "rotatinghome.com",
        "router-switch.com",
        "roytuts.com",
        "royvanrijn.com",
        "rpubs.com",
        "rrwebfetch.com",
        "ruby-china.org",
        "rubydoc.info",
        "ruger.com",
        "runestone.academy",
        "safegraph.com",
        "salesforcetutorial.com",
        "sankeymatic.com",
        "sapbazar.com",
        "saptechnical.com",
        "sascha-frank.com",
        "sassnet.com",
        "sbarjatiya.com",
        "sbof.com",
        "sc.edu",
        "scala-lang.org",
        "scalelab.com",
        "scalyr.com",
        "scantips.com",
        "schedmd.com",
        "schellscenic.com",
        "scipy.org",
        "scott.plus",
        "screen-size.info",
        "sctoolcorp.com",
        "secureteen.com",
        "self.gutenberg.org",
        "semantic-kitti.org",
        "sequelpro.com",
        "serversmtp.com",
        "sfsuperiorcourt.org",
        "shoelace.io",
        "shotcut.org",
        "shrm.org",
        "shrubbery.net",
        "sidebranch.com",
        "signal.org",
        "simpragma.com",
        "sinclair.edu",
        "sites.google.com",
        "sken.io",
        "sketchingwithcss.com",
        "skillcrush.com",
        "sltrib.com",
        "smallcultfollowing.com",
        "smallsurething.com",
        "snorkel.ai",
        "softschools.com",
        "soundswitch.com",
        "sourcedaddy.com",
        "sourceware.org",
        "spblog.net",
        "specialtyproduce.com",
        "spectrumbusiness.net",
        "spreadsheet1.com",
        "sqlines.com",
        "sqlite.org",
        "sqlmatters.com",
        "sqlusa.com",
        "stackabuse.com",
        "stackshare.io",
        "stahlworks.com",
        "stardewvalleywiki.com",
        "startupleadership.com",
        "startx.com",
        "stateofopendata.od4d.net",
        "stateparks.com",
        "statlect.com",
        "statpower.net",
        "stefan.buettcher.org",
        "stepzen.com",
        "stilltasty.com",
        "stormotion.io",
        "strftime.net",
        "structurely.com",
        "styled-components.com",
        "sumopaint.com",
        "support.cc.gatech.edu",
        "support.earthlink.net",
        "support.hp.com",
        "survivalservers.com",
        "swmath.org",
        "tableizer.journalistopia.com",
        "tabulator.info",
        "tailscale.com",
        "taskworld.com",
        "tcl.tk",
        "teacherzone.com",
        "techbrood.com",
        "techdatacloud.eu",
        "techmeme.com",
        "telematika.org",
        "temporal.io",
        "texdoc.net",
        "textem.net",
        "tfidf.com",
        "tfsbillpay.com",
        "thebitguru.com",
        "thecinemaholic.com",
        "thefouriertransform.com",
        "thegamesjournal.com",
        "theinfatuation.com",
        "theoatmeal.com",
        "theoutbound.com",
        "thepattern.com",
        "thesassway.com",
        "theweek.com",
        "thexlab.com",
        "thinkingwithaline.com",
        "thomas-cokelaer.info",
        "tidelift.com",
        "tigercolor.com",
        "time-time.net",
        "time.gov",
        "timebie.com",
        "timestampconvert.com",
        "tizag.com",
        "tomveatch.com",
        "tracktherecovery.org",
        "trankynam.com",
        "trustedcomputinggroup.org",
        "tug.org",
        "turncameraon.com",
        "tutanota.com",
        "tutorialkart.com",
        "twc.texas.gov",
        "ubackup.com",
        "ubiqx.org",
        "ucet.org",
        "udates.com",
        "uh.edu",
        "uhcl.edu",
        "ui.nv.gov",
        "ultralinux.org",
        "umich.edu",
        "umkc.edu",
        "unicode.org",
        "uninstallmacapp.com",
        "unitronicsplc.com",
        "universalclass.com",
        "unixwiz.net",
        "unknownroad.com",
        "unraid.net",
        "update.microsoft.com",
        "usaco.org",
        "usacocoach.com",
        "usalearns.org",
        "useragentstring.com",
        "uservoice.com",
        "usg.edu",
        "usmle.org",
        "utdallas.edu",
        "utf8-chartable.de",
        "valgrind.org",
        "vassarstats.net",
        "vecta.io",
        "verilog.renerta.com",
        "vertabelo.com",
        "vfsforgit.org",
        "virtualmin.com",
        "visuallink.com",
        "vizito.be",
        "voyteklab.com",
        "w3resource.com",
        "walterfootball.com",
        "warecentral.com",
        "warren-selbert.com",
        "watchful.io",
        "way2tutorial.com",
        "wdwinfo.com",
        "wealthobjects.com",
        "weatherstreet.com",
        "webdataextractionservices.com",
        "webmath.com",
        "webmin.com",
        "webscraper.io",
        "webstyleguide.com",
        "weknowinc.com",
        "wi-fi.org",
        "wickedlysmart.com",
        "wickham43.net",
        "williamyaoh.com",
        "windstream.com",
        "wingdb.com",
        "winged.ch",
        "winginx.com",
        "wordcount.com",
        "workflow.is",
        "worldclim.org",
        "worldofleveldesign.com",
        "wowgold.hk",
        "wowinterface.com",
        "wpowerproducts.com",
        "writebetteremails.com",
        "wsdot.wa.gov",
        "x-rates.com",
        "xahlee.info",
        "xcprod.com",
        "xe.com",
        "xignite.com",
        "xmlgrid.net",
        "xmpp.net",
        "xor.pw",
        "xspdf.com",
        "yourcoach.be",
        "zagat.com",
        "zapatopi.net",
        "zencephalon.com",
        "zim-wiki.org",
        "zinstall.com",
        "zipmap.net",
        "zlib.net",
        "zmenu.com",
        "zoneminder.com",
        "zvon.org"
    )

    private val lowerPathDomains = listOf(
        "247sports.com",
        "3cx.com",
        "8notes.com",
        "8onthepark.com",
        "a-z-animals.com",
        "aao.org",
        "abbreviations.com",
        "abc.virginia.gov",
        "abcam.com",
        "abebooks.com",
        "acc.org",
        "accenture.com",
        "access.redhat.com",
        "accessdata.fda.gov",
        "account.live.com",
        "accounts.google.com",
        "acefitness.org",
        "acehardware.com",
        "achieve.lausd.net",
        "acog.org",
        "acronymfinder.com",
        "acronyms.thefreedictionary.com",
        "active.com",
        "adoptapet.com",
        "ads.google.com",
        "adt.com",
        "af.mil",
        "agingcare.com",
        "ahajournals.org",
        "aicpa.org",
        "airforcemag.com",
        "airnav.com",
        "ajronline.org",
        "alaskaair.com",
        "allaboutbirds.org",
        "alleywatch.com",
        "almanac.com",
        "altaro.com",
        "altova.com",
        "alz.org",
        "amazon.com",
        "amd.com",
        "americanexpress.com",
        "amfam.com",
        "ams.usda.gov",
        "anaconda.org",
        "analog.com",
        "answers.acrobatusers.com",
        "ansys.com",
        "anthem.com",
        "any.do",
        "aopa.org",
        "api.jquery.com",
        "apidock.com",
        "app.leg.wa.gov",
        "appliancesconnection.com",
        "applitrack.com",
        "aqua-calc.com",
        "ar15.com",
        "arborday.org",
        "archdaily.com",
        "arduino.cc",
        "ark-funds.com",
        "army.mil",
        "armypubs.army.mil",
        "artistsnetwork.com",
        "artstation.com",
        "ascd.org",
        "asha.org",
        "ask.slashdot.org",
        "assessor.co.la.ca.us",
        "assets.hcca-info.org",
        "asus.com",
        "athletic.net",
        "atom.io",
        "atptour.com",
        "atriumhealth.org",
        "austintexas.org",
        "autoanything.com",
        "autotrader.com",
        "avery.com",
        "aviewfrommyseat.com",
        "aws.org",
        "azaleabarcodes.com",
        "azdor.gov",
        "azdot.gov",
        "babynames.com",
        "babynamewizard.com",
        "backmarket.com",
        "ballarddesigns.com",
        "bank-code.net",
        "batteriesplus.com",
        "behance.net",
        "belkin.com",
        "benefits.gov",
        "benjaminmoore.com",
        "bergdorfgoodman.com",
        "bestcase.com",
        "betterhealth.vic.gov.au",
        "bettycrocker.com",
        "bevnet.com",
        "bible.com",
        "bible.knowing-jesus.com",
        "bibme.org",
        "big5sportinggoods.com",
        "biggerpockets.com",
        "biglots.com",
        "billtrack50.com",
        "binance.com",
        "bisnow.com",
        "bizbuysell.com",
        "bl.ocks.org",
        "blackwasp.co.uk",
        "blockchain.com",
        "blocksite.co",
        "blog.csdn.net",
        "blog.hootsuite.com",
        "blog.hubspot.com",
        "blog.mozilla.org",
        "blogs.bing.com",
        "blogs.oracle.com",
        "bls.gov",
        "blueshieldca.com",
        "bluestoneperennials.com",
        "boattrader.com",
        "bogleheads.org",
        "bookbrowse.com",
        "bookdepository.com",
        "brickset.com",
        "brightcomputing.com",
        "britishairways.com",
        "brokercheck.finra.org",
        "brother-usa.com",
        "brownells.com",
        "budsgunshop.com",
        "bulbapedia.bulbagarden.net",
        "businessinsider.in",
        "businessnamegenerator.com",
        "buy.garmin.com",
        "c-sharpcorner.com",
        "caesars.com",
        "calbar.ca.gov",
        "calendar-12.com",
        "callofduty.com",
        "calrecycle.ca.gov",
        "canr.msu.edu",
        "capitalgroup.com",
        "carbonhealth.com",
        "cardgames.app",
        "carecredit.com",
        "careeronestop.org",
        "cash.app",
        "catalog.hardydiagnostics.com",
        "cde.ca.gov",
        "cdn.ymaws.com",
        "cdph.ca.gov",
        "cdss.ca.gov",
        "cdw.com",
        "cedargraphicsinc.com",
        "cedarville.edu",
        "century21.com",
        "cesarsway.com",
        "cga.ct.gov",
        "chabad.org",
        "champion.gg",
        "channel4.com",
        "channel9.msdn.com",
        "chatsports.com",
        "cheapflights.com",
        "chemicalbook.com",
        "chemocare.com",
        "chicagobooth.edu",
        "chicagomag.com",
        "choosechicago.com",
        "chortle.ccsu.edu",
        "chp.ca.gov",
        "christies.com",
        "cia.gov",
        "cibmtr.org",
        "cincinnatichildrens.org",
        "cis.temple.edu",
        "cityofberkeley.info",
        "cityofsacramento.org",
        "ck12.org",
        "cleartax.in",
        "clickondetroit.com",
        "cmich.edu",
        "cms.gov",
        "code.visualstudio.com",
        "codedaily.io",
        "codefresh.io",
        "codeproject.com",
        "coecsl.ece.illinois.edu",
        "coinmarketcap.com",
        "coinsutra.com",
        "collab.its.virginia.edu",
        "columbus.gov",
        "community.adobe.com",
        "community.chocolatey.org",
        "community.hpe.com",
        "community.windows.com",
        "compellingtruth.org",
        "comptroller.texas.gov",
        "conceptcarz.com",
        "conjugator.reverso.net",
        "consumercellular.com",
        "content.techgig.com",
        "context.reverso.net",
        "controller.com",
        "costco.com",
        "costcobusinessdelivery.com",
        "costcotravel.com",
        "courts.state.va.us",
        "covers.com",
        "cpuc.ca.gov",
        "crateandbarrel.com",
        "creately.com",
        "cricbuzz.com",
        "criswellchryslerjeepdodge.com",
        "crossword-solver.io",
        "crucial.com",
        "crwflags.com",
        "cs.cornell.edu",
        "csis.ul.ie",
        "csrc.nist.gov",
        "csus.edu",
        "csusm.edu",
        "ctimls.com",
        "currency-converter-calculator.com",
        "curseforge.com",
        "cutepdf.com",
        "cwiki.apache.org",
        "d.comenity.net",
        "dallascityhall.com",
        "data.worldbank.org",
        "datetime360.com",
        "db-engines.com",
        "defense.gov",
        "definitions.net",
        "delawareinc.com",
        "dell.com",
        "denvergov.org",
        "depts.ttu.edu",
        "developer.amazon.com",
        "developer.apple.com",
        "developer.ebay.com",
        "developer.mozilla.org",
        "developer.nvidia.com",
        "developers.exlibrisgroup.com",
        "deviantart.com",
        "dfas.mil",
        "dhcs.ca.gov",
        "dhs.state.il.us",
        "dice.com",
        "dict.hinkhoj.com",
        "digitalcommerce360.com",
        "dignityhealth.org",
        "dir.ca.gov",
        "discord.com",
        "discounttire.com",
        "disneyland.disney.go.com",
        "disneyworld.disney.go.com",
        "dispatch.com",
        "distrowatch.com",
        "diys.com",
        "dla.mil",
        "dmarcanalyzer.com",
        "dnr.wi.gov",
        "doc.qt.io",
        "docs.actian.com",
        "docs.microsoft.com",
        "docs.splunk.com",
        "documentation.solarwinds.com",
        "dogster.com",
        "dogtrekker.com",
        "doh.sd.gov",
        "doh.wa.gov",
        "dol.gov",
        "dollar.com",
        "dollartree.com",
        "downdetector.com",
        "download.autodesk.com",
        "dps.texas.gov",
        "dribbble.com",
        "drivers.softpedia.com",
        "driversed.com",
        "dsw.com",
        "duke-energy.com",
        "dupontregistry.com",
        "earthobservatory.nasa.gov",
        "ebi.ac.uk",
        "ebridgeconnections.com",
        "economictimes.indiatimes.com",
        "ed.gov",
        "edd.ca.gov",
        "edhrec.com",
        "editorial.rottentomatoes.com",
        "efile.com",
        "eguruchela.com",
        "eia.gov",
        "elsevier.com",
        "emerald.com",
        "emergeinteractive.com",
        "emerson.com",
        "emirates.com",
        "en.bitcoin.it",
        "en.bitcoinwiki.org",
        "en.help.roblox.com",
        "en.wikibooks.org",
        "en.wikipedia.org",
        "en.wiktionary.org",
        "energystar.gov",
        "engineering.com",
        "engineering.purdue.edu",
        "entnemdept.ufl.edu",
        "epguides.com",
        "equifax.com",
        "es.wikipedia.org",
        "esv.org",
        "etherscan.io",
        "etrailer.com",
        "etymonline.com",
        "europepmc.org",
        "evga.com",
        "ewg.org",
        "exploratorium.edu",
        "extension.iastate.edu",
        "faa.gov",
        "facebook.com",
        "fairfaxcounty.gov",
        "familytreemagazine.com",
        "famousfootwear.com",
        "fandangonow.com",
        "fao.org",
        "farfetch.com",
        "fast-growing-trees.com",
        "fdic.gov",
        "federalreserve.gov",
        "ferris.edu",
        "file-intelligence.comodo.com",
        "fileformat.info",
        "finalsitesupport.com",
        "finance.yahoo.com",
        "financhill.com",
        "financial-dictionary.thefreedictionary.com",
        "findagrave.com",
        "finewoodworking.com",
        "finishline.com",
        "finra.org",
        "fishersci.com",
        "flightradar24.com",
        "flightstats.com",
        "flightview.com",
        "flixed.io",
        "flooranddecor.com",
        "floridastateparks.org",
        "fmsinc.com",
        "fontspace.com",
        "fontsquirrel.com",
        "forever21.com",
        "forgetcode.com",
        "forsalebyowner.com",
        "fox2now.com",
        "fred.stlouisfed.org",
        "freelancer.com",
        "frontier.com",
        "ftb.ca.gov",
        "fueleconomy.gov",
        "funtrivia.com",
        "fws.gov",
        "fxstreet.com",
        "gadgetsnow.com",
        "gao.gov",
        "gatherer.wizards.com",
        "gearbest.com",
        "genome.ucsc.edu",
        "geo.craigslist.org",
        "geokov.com",
        "getroost.zendesk.com",
        "gettyimages.com",
        "gfycat.com",
        "gifts.com",
        "gismaps.kingcounty.gov",
        "gist.github.com",
        "github.blog",
        "github.com",
        "gitter.im",
        "glassdoor.com",
        "globalair.com",
        "gohugo.io",
        "governing.com",
        "governmentjobs.com",
        "govtech.com",
        "grammarbook.com",
        "grants.nih.gov",
        "grc.nasa.gov",
        "greatergood.berkeley.edu",
        "greentechmedia.com",
        "grok.lsu.edu",
        "guns.com",
        "gunsamerica.com",
        "gurufocus.com",
        "haas.berkeley.edu",
        "hagerty.com",
        "hallmark.com",
        "har.com",
        "harborfreight.com",
        "hawaiianairlines.com",
        "hbs.edu",
        "health.harvard.edu",
        "health.ucsd.edu",
        "healthcare.ascension.org",
        "healthcare.gov",
        "healthy.kaiserpermanente.org",
        "healthychildren.org",
        "help.aweber.com",
        "help.calendly.com",
        "help.dreamhost.com",
        "help.figma.com",
        "help.hbomax.com",
        "help.hotjar.com",
        "help.minecraft.net",
        "help.nytimes.com",
        "help.parsehub.com",
        "help.zearn.org",
        "helpcenter.steinberg.de",
        "hendrix.edu",
        "higheredjobs.com",
        "hipaaspace.com",
        "hltv.org",
        "hme-business.com",
        "hmhbooks.com",
        "homedit.com",
        "hopkinsmedicine.org",
        "hostsearch.com",
        "houseofnames.com",
        "houstonisd.org",
        "howardhanna.com",
        "howtogeek.com",
        "hrc.org",
        "htmlgoodies.com",
        "hud.gov",
        "huduser.gov",
        "humana.com",
        "huntington.com",
        "hy-vee.com",
        "icewalkers.com",
        "icicibank.com",
        "iconarchive.com",
        "icons8.com",
        "identitytheft.gov",
        "iep.online-iep.com",
        "iep.utm.edu",
        "iherb.com",
        "ilga.gov",
        "imf.org",
        "imslp.org",
        "in.finance.yahoo.com",
        "indeed.com",
        "inflectra.com",
        "infoq.com",
        "institutionalinvestor.com",
        "internet-ink.com",
        "investor.vanguard.com",
        "investorshub.advfn.com",
        "investorsobserver.com",
        "iphonehacks.com",
        "iristech.co",
        "isc2.org",
        "isitdownrightnow.com",
        "jabra.com",
        "jacksonville.com",
        "jaksta.com",
        "jameco.com",
        "jasinskionline.com",
        "jdpower.com",
        "jea.com",
        "joebiden.com",
        "jotform.com",
        "journals.lww.com",
        "jpost.com",
        "jwpepper.com",
        "kb.intermedia.net",
        "kb.mit.edu",
        "kb.netgear.com",
        "keepitsafe.com",
        "kellogg.northwestern.edu",
        "khwiki.com",
        "kidney.org",
        "kids.britannica.com",
        "kite.com",
        "klwines.com",
        "knowledge.autodesk.com",
        "knowledge.hubspot.com",
        "kongregate.com",
        "kryteriononline.com",
        "kycourts.gov",
        "kylesconverter.com",
        "landsofamerica.com",
        "larksuite.com",
        "law2.umkc.edu",
        "lawdepot.com",
        "lcps.org",
        "learn.saylor.org",
        "learnopengl.com",
        "leetcode.com",
        "leg.state.nv.us",
        "legal-dictionary.thefreedictionary.com",
        "legis.state.pa.us",
        "lenscrafters.com",
        "lexisnexis.com",
        "libguides.library.kent.edu",
        "lichess.org",
        "lifehack.org",
        "linkedin.com",
        "linux.com",
        "linuxconfig.org",
        "linuxfoundation.org",
        "literarydevices.net",
        "livenation.com",
        "localcabledeals.com",
        "ltcconline.net",
        "ludwig.guru",
        "lw.com",
        "lyft.com",
        "lynda.com",
        "machinio.com",
        "macmost.com",
        "macobserver.com",
        "macroaxis.com",
        "macrumors.com",
        "macstories.net",
        "mail.google.com",
        "makemytrip.com",
        "makeschool.com",
        "makeupalley.com",
        "malegislature.gov",
        "mamanatural.com",
        "marcustheatres.com",
        "maricopa.gov",
        "mariowiki.com",
        "marketplace.xbox.com",
        "marketwatch.com",
        "massgeneral.org",
        "mastercook.com",
        "masterofmalt.com",
        "mathcentral.uregina.ca",
        "mayoclinic.org",
        "mbusa.com",
        "mckinsey.com",
        "mcmaster.com",
        "med.umich.edu",
        "med.unc.edu",
        "mediawiki.org",
        "medical-dictionary.thefreedictionary.com",
        "medicare.gov",
        "megamillions.com",
        "memedroid.com",
        "merriam-webster.com",
        "merrilledge.com",
        "metal-archives.com",
        "methods.sagepub.com",
        "metopera.org",
        "microcenter.com",
        "microsoft.com",
        "mindtools.com",
        "minecraft.fandom.com",
        "missionlocal.org",
        "mkyong.com",
        "mobilelinkgen.zendesk.com",
        "models.com",
        "mondaq.com",
        "monoprice.com",
        "monster.com",
        "montgomerycountymd.gov",
        "moodys.com",
        "morganlewis.com",
        "morningstar.com",
        "mouser.com",
        "msi.com",
        "msn.com",
        "msnbc.com",
        "muscleandstrength.com",
        "mxtoolbox.com",
        "my.napier.ac.uk",
        "myanimelist.net",
        "myfloridacfo.com",
        "myhealth.alberta.ca",
        "mylifetime.zendesk.com",
        "myweather2.com",
        "n.rivals.com",
        "na.op.gg",
        "nadaguides.com",
        "name.com",
        "namecheap.com",
        "nami.org",
        "nashville.gov",
        "nationalgridus.com",
        "nb.fidelity.com",
        "nbcnews.com",
        "nces.ed.gov",
        "ncsl.org",
        "needtags.com",
        "nejm.org",
        "netflix.com",
        "netgear.com",
        "netspotapp.com",
        "newbalance.com",
        "newegg.com",
        "news.gallup.com",
        "news.microsoft.com",
        "newschool.edu",
        "newworldencyclopedia.org",
        "nga.org",
        "nglish.com",
        "niceonecode.com",
        "nike.com",
        "nikonusa.com",
        "ninds.nih.gov",
        "niu.edu",
        "npm.io",
        "npmjs.com",
        "nucleus.iaea.org",
        "nurse.org",
        "nvidia.com",
        "nwf.org",
        "nysenate.gov",
        "nytco.com",
        "obamawhitehouse.archives.gov",
        "ods.od.nih.gov",
        "offensive-security.com",
        "office.live.com",
        "ohchr.org",
        "oldschool.runescape.wiki",
        "olt.com",
        "onenote.com",
        "oodlestechnologies.com",
        "opm.gov",
        "optimum.net",
        "oregon.gov",
        "oreillyauto.com",
        "orvis.com",
        "osha.gov",
        "outlook.live.com",
        "outsystems.com",
        "overleaf.com",
        "overstock.com",
        "paganresearch.io",
        "panjiva.com",
        "parallels.com",
        "parks.ca.gov",
        "passportsandvisas.com",
        "patient.info",
        "paxful.com",
        "paypal.com",
        "pcoservices.zendesk.com",
        "pe.usps.com",
        "peacehealth.org",
        "pearsonsupport.helpserve.com",
        "penpublishing.com",
        "peoplekeep.com",
        "perfectgame.org",
        "petersons.com",
        "pexels.com",
        "pfaf.org",
        "pga.com",
        "phila.gov",
        "philpapers.org",
        "phoenix.gov",
        "phrogz.net",
        "physicsclassroom.com",
        "physio-pedia.com",
        "pkg.go.dev",
        "plannedparenthood.org",
        "plasticsurgery.org",
        "player.fm",
        "playstationtrophies.org",
        "plugins.jetbrains.com",
        "podbean.com",
        "police1.com",
        "porsche.com",
        "portal.ct.gov",
        "portswigger.net",
        "poshmark.com",
        "postofficeshours.com",
        "poundsterlinglive.com",
        "practicalecommerce.com",
        "predictiveanalyticstoday.com",
        "premierleague.com",
        "priceintelligently.com",
        "privacy.microsoft.com",
        "probuilds.net",
        "process.st",
        "productschool.com",
        "protocol.com",
        "providence.org",
        "providencejournal.com",
        "prowritingaid.com",
        "proz.com",
        "psacard.com",
        "pubchem.ncbi.nlm.nih.gov",
        "public.com",
        "public.navy.mil",
        "publichealth.lacounty.gov",
        "pythontic.com",
        "quotes.net",
        "racefans.net",
        "radiologyinfo.org",
        "rapidapi.com",
        "rationalwiki.org",
        "raymondjames.com",
        "rcsb.org",
        "redmondmag.com",
        "reference.codeproject.com",
        "regions.com",
        "renaissancecapital.com",
        "renewalbyandersen.com",
        "rentalcars.com",
        "rentals.com",
        "repairclinic.com",
        "repl.it",
        "reservations.com",
        "resources.esri.com",
        "resources.sei.cmu.edu",
        "revenue.wi.gov",
        "reviews.io",
        "rhs.org.uk",
        "riteaid.com",
        "robertsspaceindustries.com",
        "robinhood.com",
        "roblox.com",
        "rochester.edu",
        "ronsplace.eu",
        "rosettacode.org",
        "rsc.org",
        "runescape.wiki",
        "runningwarehouse.com",
        "rv.campingworld.com",
        "rvt.com",
        "rvusa.com",
        "sajeconsultants.com",
        "salliemae.com",
        "santanderbank.com",
        "sba.com",
        "sccgov.org",
        "scdhec.gov",
        "scholarships.com",
        "schools.nyc.gov",
        "schwab.wallst.com",
        "sciencebuddies.org",
        "sciencenewsforstudents.org",
        "scipy.github.io",
        "scouting.org",
        "searchengineland.com",
        "seattle.gov",
        "seattlechildrens.org",
        "seattlepi.com",
        "secure.n-able.com",
        "self.gutenberg.org",
        "services.flhsmv.gov",
        "sfdph.org",
        "sfgov.org",
        "sfmoma.org",
        "sfrecpark.org",
        "shift.newco.co",
        "ship24.com",
        "shop.lululemon.com",
        "shopbop.com",
        "shrm.org",
        "shutterstock.com",
        "si.edu",
        "sim-unlock.net",
        "simpleindex.com",
        "simplethread.com",
        "sixflags.com",
        "skybrary.aero",
        "slack.com",
        "slang.org",
        "smu.edu",
        "socialblade.com",
        "sodapdf.com",
        "softwaredaily.com",
        "sophos.com",
        "soundcloud.com",
        "specialized.com",
        "speedrun.com",
        "sphweb.bumc.bu.edu",
        "sportslogos.net",
        "sportsmansoutdoorsuperstore.com",
        "ssa.gov",
        "stackoverflow.com",
        "stagraph.com",
        "stardewvalleywiki.com",
        "starsunfolded.com",
        "startingyourbusiness.com",
        "starwars.com",
        "statefarm.com",
        "stevefenton.co.uk",
        "stilltasty.com",
        "stlouis-mo.gov",
        "stock.adobe.com",
        "stocknews.com",
        "stockrow.com",
        "stocktwits.com",
        "streamlabs.com",
        "summitracing.com",
        "sunrisesunset.com",
        "supermicro.com",
        "supplychain247.com",
        "support.3dcart.com",
        "support.airtable.com",
        "support.apple.com",
        "support.appsflyer.com",
        "support.befunky.com",
        "support.bell.ca",
        "support.bitly.com",
        "support.discord.com",
        "support.gusto.com",
        "support.hp.com",
        "support.knowbe4.com",
        "support.kraken.com",
        "support.lenovo.com",
        "support.motorola.com",
        "support.netdocuments.com",
        "support.onepeloton.com",
        "support.ring.com",
        "support.roku.com",
        "support.shippingeasy.com",
        "support.shotgunsoftware.com",
        "support.shutterfly.com",
        "support.skype.com",
        "support.spotify.com",
        "support.squarespace.com",
        "support.stackpath.com",
        "support.strava.com",
        "support.taxslayer.com",
        "support.taxslayerpro.com",
        "support.techsmith.com",
        "support.ti.davidson.edu",
        "support.twilio.com",
        "support.ubisoft.com",
        "support.zendesk.com",
        "support.zoom.us",
        "supportcenter.devexpress.com",
        "supremecourt.gov",
        "synonyms.com",
        "t-mobile.com",
        "t.me",
        "tailorbrands.com",
        "tarladalal.com",
        "taxact.com",
        "taxpolicycenter.org",
        "tdwi.org",
        "teamusa.org",
        "techgenix.com",
        "techsoup.org",
        "telegram.com",
        "templates.office.com",
        "tennis-warehouse.com",
        "tensorflow.org",
        "tesla.com",
        "theamericancollege.edu",
        "thegazette.com",
        "thehustle.co",
        "theinformation.com",
        "themoneyconverter.com",
        "therealreal.com",
        "thingiverse.com",
        "thriftbooks.com",
        "ti.com",
        "tiaa.org",
        "ticketmaster.com",
        "tidal.com",
        "tileteam.zendesk.com",
        "time.is",
        "tldrlegal.com",
        "toasttab.com",
        "tourtexas.com",
        "toyota.com",
        "toywiz.com",
        "tp-link.com",
        "tractorsupply.com",
        "traderjoes.com",
        "translatorscafe.com",
        "transportnsw.info",
        "travel.usnews.com",
        "travelawaits.com",
        "travelchinaguide.com",
        "travelok.com",
        "treasury.gov",
        "treasurydirect.gov",
        "trekbikes.com",
        "trendmicro.com",
        "tributearchive.com",
        "tripplite.com",
        "tutorial.math.lamar.edu",
        "tutorialdost.com",
        "tutorialsteacher.com",
        "tvtropes.org",
        "twitch.tv",
        "twitter.com",
        "uaex.edu",
        "ucanr.edu",
        "uclahealth.org",
        "uhaul.com",
        "uhhospitals.org",
        "uk.finance.yahoo.com",
        "uline.com",
        "uml.edu",
        "un.org",
        "uncw.edu",
        "underwaterphotography.com",
        "united.com",
        "unitypoint.org",
        "unix.com",
        "uphe.com",
        "upmc.com",
        "ups.com",
        "urban.org",
        "us.kohler.com",
        "usa.canon.com",
        "usa.gov",
        "usajobs.gov",
        "usermanual.wiki",
        "ushistory.org",
        "va.gov",
        "virginia.org",
        "virginiamason.org",
        "visaprepaidprocessing.com",
        "visitorlando.com",
        "visitutah.com",
        "visualstudiomagazine.com",
        "vitacost.com",
        "vocabulary.com",
        "vudu.com",
        "w3.org",
        "w3schools.com",
        "walgreens.com",
        "walmart.com",
        "walterfootball.com",
        "washington.org",
        "wattpad.com",
        "way.com",
        "wdwinfo.com",
        "wearedevs.net",
        "weather-and-climate.com",
        "weather.gov",
        "web.mit.edu",
        "weber.com",
        "webflow.com",
        "weblog.west-wind.com",
        "webpages.uidaho.edu",
        "webqc.org",
        "website.com",
        "webster-dictionary.org",
        "wellesley.edu",
        "wellsfargo.com",
        "wesm.github.io",
        "westernunion.com",
        "wh40k.lexicanum.com",
        "whatbox.ca",
        "whitman.edu",
        "whitney.org",
        "who.int",
        "wickedlocal.com",
        "wiki.archlinux.org",
        "wiki.factorio.com",
        "wiki.openstreetmap.org",
        "wiki.python.org",
        "wiki.vyos.net",
        "wikitravel.org",
        "wikitree.com",
        "wikizero.com",
        "wildlife.ca.gov",
        "wilsonbrosgardens.com",
        "winespectator.com",
        "wisconsindot.gov",
        "wolterskluwer.com",
        "woocommerce.com",
        "wordplays.com",
        "worldofwarcraft.com",
        "wowwiki-archive.fandom.com",
        "wsdot.com",
        "wsdot.wa.gov",
        "wtae.com",
        "wtatennis.com",
        "wwnorton.com",
        "www1.maths.leeds.ac.uk",
        "www1.nationalgridus.com",
        "www1.salary.com",
        "www2.advantech.com",
        "www2.calstate.edu",
        "www2.chemistry.msu.edu",
        "www2.illinois.gov",
        "www3.nd.edu",
        "www3.ntu.edu.sg",
        "www8.hp.com",
        "wwwnc.cdc.gov",
        "wyzant.com",
        "xbox.com",
        "xboxachievements.com",
        "youglish.com",
        "yourtango.com",
        "zamzar.com",
        "zeenews.india.com",
        "zoominfo.com",
        "zumiez.com"
    )
}
